CREATE TABLE inputs2 (
  id INTEGER PRIMARY KEY,
  status INTEGER NOT NULL,
  v_pv NUMERIC NOT NULL,
  v_pv_1 NUMERIC NOT NULL,
  v_pv_2 NUMERIC NOT NULL,
  v_pv_3 NUMERIC NOT NULL,
  v_bat NUMERIC NOT NULL,
  soc INTEGER NOT NULL,
  soh INTEGER NOT NULL,
  p_pv INTEGER NOT NULL,
  p_pv_1 INTEGER NOT NULL,
  p_pv_2 INTEGER NOT NULL,
  p_pv_3 INTEGER NOT NULL,
  p_charge INTEGER NOT NULL,
  p_discharge INTEGER NOT NULL,
  v_ac_r NUMERIC NOT NULL,
  v_ac_s NUMERIC NOT NULL,
  v_ac_t NUMERIC NOT NULL,
  f_ac NUMERIC NOT NULL,
  p_inv INTEGER NOT NULL,
  p_rec INTEGER NOT NULL,
  p_eps INTEGER NOT NULL,
  s_eps INTEGER NOT NULL,
  pf NUMERIC NOT NULL,
  v_eps_r NUMERIC NOT NULL,
  v_eps_s NUMERIC NOT NULL,
  v_eps_t NUMERIC NOT NULL,
  f_eps NUMERIC NOT NULL,
  p_to_grid INTEGER NOT NULL,
  p_to_user INTEGER NOT NULL,
  e_pv_day NUMERIC NOT NULL,
  e_pv_day_1 NUMERIC NOT NULL,
  e_pv_day_2 NUMERIC NOT NULL,
  e_pv_day_3 NUMERIC NOT NULL,
  e_inv_day NUMERIC NOT NULL,
  e_rec_day NUMERIC NOT NULL,
  e_chg_day NUMERIC NOT NULL,
  e_dischg_day NUMERIC NOT NULL,
  e_eps_day NUMERIC NOT NULL,
  e_to_grid_day NUMERIC NOT NULL,
  e_to_user_day NUMERIC NOT NULL,
  v_bus_1 NUMERIC NOT NULL,
  v_bus_2 NUMERIC NOT NULL,

  e_pv_all NUMERIC NOT NULL,
  e_pv_all_1 NUMERIC NOT NULL,
  e_pv_all_2 NUMERIC NOT NULL,
  e_pv_all_3 NUMERIC NOT NULL,
  e_inv_all NUMERIC NOT NULL,
  e_rec_all NUMERIC NOT NULL,
  e_chg_all NUMERIC NOT NULL,
  e_dischg_all NUMERIC NOT NULL,
  e_eps_all NUMERIC NOT NULL,
  e_to_grid_all NUMERIC NOT NULL,
  e_to_user_all NUMERIC NOT NULL,
  t_inner INTEGER NOT NULL,
  t_rad_1 INTEGER NOT NULL,
  t_rad_2 INTEGER NOT NULL,
  t_bat INTEGER NOT NULL,
  runtime INTEGER NOT NULL,

  max_chg_curr NUMERIC,
  max_dischg_curr NUMERIC,
  charge_volt_ref NUMERIC,
  dischg_cut_volt NUMERIC,
  bat_status_0 INTEGER,
  bat_status_1 INTEGER,
  bat_status_2 INTEGER,
  bat_status_3 INTEGER,
  bat_status_4 INTEGER,
  bat_status_5 INTEGER,
  bat_status_6 INTEGER,
  bat_status_7 INTEGER,
  bat_status_8 INTEGER,
  bat_status_9 INTEGER,
  bat_status_inv INTEGER,
  bat_count INTEGER,
  bat_capacity INTEGER,

  bat_current NUMERIC,
  bms_event_1 INTEGER,
  bms_event_2 INTEGER,
  max_cell_voltage NUMERIC,
  min_cell_voltage NUMERIC,
  max_cell_temp NUMERIC,
  min_cell_temp NUMERIC,
  bms_fw_update_state INTEGER,
  cycle_count INTEGER,
  vbat_inv NUMERIC,

  datalog TEXT NOT NULL,
  created_at DATETIME NOT NULL
);

INSERT INTO inputs2 SELECT * FROM inputs;
DROP TABLE inputs;
ALTER TABLE inputs2 RENAME TO inputs;
